config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  post 'users/access', to: "users#access"
  get 'users/logout'
  get 'users/login'
  get 'questions/menu', to: "questions#menu"
  get 'answers/megusta/:id', to: "answers#megusta"
  get 'answers/medisgusta/:id', to: "answers#medisgusta"

  resources :users
  resources :questions
  resources :answers

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base

  has_many :answers

end

app/models/user.rb
class User < ActiveRecord::Base
  include BCrypt


  def password
    @password ||= Password.new(password_digest)
  end

  def password=(user_password)
    @password = Password.create(user_password)
    self.password_digest = @password
  end

  def self.authenticate(email, user_password)


    user = User.find_by(mail: email)

    if user && (user.password == user_password)
      return user
    else
      nil
    end
  end




end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def index
  end

  def show
    p "*" * 100
    p "*" * 100
    p "*" * 100
    p "*" * 100
    p session[:question_id] = params[:id]
    @questions = Question.find(session[:question_id])
    @answers = @questions.answers
    
  end

  def megusta

    
    p @id_question
    p answer_id = params[:id]
    @answer = Answer.find(answer_id)
    @answer.update(vote_like: (@answer.vote_like + 1))
    @answer_val = Answer.all.order(:id)

    redirect_to action: 'show', id: session[:question_id]

  end

  def medisgusta

    p "*" * 100
    p @id_question
    p answer_id = params[:id]
    @answer = Answer.find(answer_id)
    @answer.update(vote_dislike: (@answer.vote_dislike + 1))
    @answer_val = Answer.all.order(:id)

    redirect_to action: 'show', id: session[:question_id]

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :current_user

  protect_from_forgery with: :exception

  def current_user
    if session[:id]
      @current_user ||= User.find_by_id(session[:id])
    end
  end

  def logged_in?
    !current_user.nil?
  end


  helper_method :logged_in?
  helper_method :current_user

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def menu
    
  end

  def index

    @questions = Question.all

  end

  def new
   p @question = Question.new
  end

  def create
   
    p "**" * 100
    p question_val = params[:question][:question]
    new_question = Question.new(question: question_val, vote_like: 0, vote_dislike: 0)
    new_question.save
    @questions = Question.all

    render 'index'
    



  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
  end

  def new
   p @user = User.new
  end

  def create
    p user_name = params[:user][:user_name]
    p mail = params[:user][:mail]
    p password = params[:user][:password]

    

    if logged_in?
      user = User.find_by(user_name: user_name)
      user.update(user_name: user_name, mail: mail, password: password)
      flash[:edit_message] = "Tus datos fueron editados"
      render 'index'

    else
      @user = User.new(user_name: user_name, mail: mail, password: password)
      if @user.save
        flash[:create_message] = "Tus datos fueron editados"
        render 'index'
      else
        render 'new'
      end
    end


  end

  def login
  end

  def access
    @user_mail = params[:mail]
     p @user_mail
    @user_pass = params[:password].pop
     p @user_pass
    val_user = User.authenticate(@user_mail, @user_pass)
    p val_user
    # p @val_user
    if val_user
      session[:id] = val_user.id
      session[:password] = val_user.password
      session[:email] = val_user.mail
      session[:user_name] = val_user.user_name
      render 'index' 
    else
      flash[:error_message] = "No son correctos tus datos"
      render 'index'
    end
  end

  def logout
    session.clear
    render 'index'
  end


  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper


end

app/views/answers/show.html.erb
<center><h1 style="color: #FF2542; font-size: 3em">Bienvenido a Fake Quora!</h1>

  <p><%= @questions.question %></p>
  
   <% @answers.each do |answer| %>   
      <span>* <%= answer.answer%> </span><br>
      <%=link_to "Me gusta " + answer.vote_like.to_s, controller: "answers", action: "megusta", id: answer.id, class: "links" %>
      <%=link_to "Me disgusta " + answer.vote_dislike.to_s, controller: "answers", action: "medisgusta", id: answer.id, class: "links" %>
      <br>
      <br>
  <%end%>


    <%= button_to "Create Answer!", questions_path, class: "button_submit", method: "get" %>
    <br>

    <%= button_to "Salir!", {controller: "users", action: "index"}, class: "button_submit", method: "get" %>

</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppQuoraRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header id="header"> <center>
<%= image_tag("Quora.ico") %>
</center></header>

<%= yield %>

</body>
</html>

app/views/questions/index.html.erb
<center><h1 style="color: #FF2542; font-size: 3em">Bienvenido a Fake Quora!</h1>

    <p id>
    <% @questions.each do |question| %>
      <%=link_to question.question, answer_path(question.id), class: "links" %><br><br>
    <%end%>
    </p>
    <br><br><br>
  


    <%= button_to "Create Question!", new_question_path, class: "button_submit", method: "get" %>
    <br>

    <%= button_to "Return!", {controller: "users", action: "index"}, class: "button_submit", method: "get" %>

</center>

app/views/questions/menu.html.erb
<center><h1 style="color: #FF2542; font-size: 3em">Bienvenido a Fake Quora!</h1>


    <%= button_to "Questions!", questions_path, class: "button_submit", method: "get" %>
    <br>

    <%= button_to "Return!", {controller: "users", action: "index"}, class: "button_submit", method: "get" %>

</center>

app/views/questions/new.html.erb
<center><h1 style="color: #FF2542; font-size: 3em">Registro!</h1>

  
  <%= form_for @question, action: "create" do |f| %>

              
    <%= f.text_field :question,   placeholder: "NewQuestion", class: "form-user" %>
    <br><br>
 
 
      <%= f.submit "New Question", class: "button_submit" %>

    <br>

  <% end %>
  <br><br>
  <%= button_to "Salir!", {controller: "users", action: "index"}, method: "get", class: "button_submit" %>


</center>

app/views/users/index.html.erb
<center><h1 style="color: #FF2542; font-size: 3em">Bienvenido a Fake Quora!</h1>

  <% if logged_in? %>
    <h3 style="color:blue">You are logged in <%=session[:user_name]%></h3>

  <% else %>
    <h3 style="color:red"><%=flash[:error_message]%></h3>
  <% end %>

  <h3 style="color:red"><%=flash[:edit_message]%></h3>
  <h3 style="color:red"><%=flash[:create_message]%></h3>


  <br>
  <% if logged_in? %>
    <%= button_to "Edit User!", { controller: "users", action: "new"}, class: "button_submit", method: "get" %>
    <br>
    <%= button_to "Quora!", { controller: "questions", action: "menu"}, class: "button_submit", method: "get" %>
    <br>
    <%= button_to "Logout!", { controller: "users", action: "logout"}, class: "button_submit", method: "get" %>
    <br>
  <% else %>
    <%= button_to "Registrar!", { controller: "users", action: "new"}, class: "button_submit",  method: "get" %>
    <br>
    <%= button_to "Login!", { controller: "users", action: "login"}, class: "button_submit", method: "get" %>
    <br>
    
  <% end %>

</center>

app/views/users/login.html.erb
<center><h1 style="color: #FF2542; font-size: 3em">Login!</h1>

  
  <%= form_tag("/users/access", method: "post")  do  %>     

    <%= email_field_tag :mail, nil,  placeholder: "Mail", class: "form-user"%>
    <br><br>
    <%= password_field :password , nil , placeholder: "Password", class: "form-user" %>
    <br><br>
    <%= submit_tag "Login!", class: "button_submit" %>
    <br>

  <% end %>
  <br>
  <br>
  <%= button_to "Salir!", {controller: "users", action: "index"}, method: "get", class: "button_submit" %>


</center>

app/views/users/new.html.erb
<center><h1 style="color: #FF2542; font-size: 3em">Registro!</h1>

  
  <%= form_for @user, action: "create" do |f| %>

              
    <%= f.text_field :user_name,   placeholder: "Usuario", class: "form-user", value: session[:user_name] %>
    <br><br>
    <%= f.email_field :mail, placeholder: "Mail", class: "form-user", value: session[:email]  %>
    <br><br>
    <%= f.password_field :password, placeholder: "Password", class: "form-user" , value: session[:password] %>
    <br><br>
    <% if logged_in? %>
      <%= f.submit "Edita", class: "button_submit" %>
    <% else %>
      <%= f.submit "Crear", class: "button_submit" %>
    <% end %>
    <br>

  <% end %>
  <br><br>
  <%= button_to "Salir!", {controller: "users", action: "index"}, method: "get", class: "button_submit" %>


</center>